# Generated by Django 3.2.16 on 2023-05-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='DetectionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SIEM', 'SIEM'), ('EDR', 'EDR')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DetectionSystem',
            },
        ),
        migrations.CreateModel(
            name='MitreTactic',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MitreTechnique',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mitre_tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitre_techniques', to='home.mitretactic')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('technologies', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=255)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='home.author')),
                ('detection_systems', models.ManyToManyField(related_name='rules', to='home.DetectionSystem')),
                ('mitre_tactics', models.ManyToManyField(related_name='rules', to='home.MitreTactic')),
                ('mitre_techniques', models.ManyToManyField(related_name='rules', to='home.MitreTechnique')),
            ],
            options={
                'db_table': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initials', models.CharField(max_length=2)),
                ('update_general_rules', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection_systems', models.ManyToManyField(related_name='customers', to='home.DetectionSystem')),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
    ]
