# Generated by Django 3.2.16 on 2023-05-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230529_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptions',
            name='expiration_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
