# Generated by Django 3.2.16 on 2023-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_exceptions_expiration_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrule',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceptions',
            name='artifact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
