# Generated by Django 3.2.16 on 2023-05-31 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230531_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceptions',
            name='artifact',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exceptions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
