# Generated by Django 3.2.16 on 2023-05-19 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230519_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrule',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Informational', 'Informational')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Informational', 'Informational')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
