# Generated by Django 3.2.16 on 2023-05-21 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20230519_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrule',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalrule',
            name='technologies',
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='rule',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='technologies',
        ),
        migrations.AlterField(
            model_name='watcher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='report',
            table='Reports',
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Technologies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTechnology',
            fields=[
                ('id', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical technology',
                'verbose_name_plural': 'historical technologys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tag',
                'verbose_name_plural': 'historical tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.ManyToManyField(related_name='reports', to='home.Tag'),
        ),
        migrations.AddField(
            model_name='report',
            name='technologies',
            field=models.ManyToManyField(related_name='reports', to='home.Technology'),
        ),
        migrations.AddField(
            model_name='watcher',
            name='tags',
            field=models.ManyToManyField(related_name='watchers', to='home.Tag'),
        ),
        migrations.AddField(
            model_name='watcher',
            name='technologies',
            field=models.ManyToManyField(related_name='watchers', to='home.Technology'),
        ),
        migrations.AddField(
            model_name='rule',
            name='tags',
            field=models.ManyToManyField(related_name='rules', to='home.Tag'),
        ),
        migrations.AddField(
            model_name='rule',
            name='technologies',
            field=models.ManyToManyField(related_name='rules', to='home.Technology'),
        ),
    ]
