# Generated by Django 3.2.16 on 2023-05-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230522_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltechnologies',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical technologies', 'verbose_name_plural': 'historical Technologies'},
        ),
        migrations.AlterModelOptions(
            name='technologies',
            options={'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterModelTable(
            name='technologies',
            table=None,
        ),
    ]
