# Generated by Django 3.2.16 on 2023-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_rule_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmitretechnique',
            name='mitre_tactic',
        ),
        migrations.RemoveField(
            model_name='mitretechnique',
            name='mitre_tactic',
        ),
        migrations.AddField(
            model_name='mitretechnique',
            name='mitre_tactics',
            field=models.ManyToManyField(related_name='mitre_techniques', to='home.MitreTactic'),
        ),
    ]
