# Generated by Django 3.2.16 on 2023-05-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230523_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmitretactic',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mitre tactic', 'verbose_name_plural': 'historical MitreTatics'},
        ),
        migrations.AlterModelOptions(
            name='historicalmitretechnique',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mitre technique', 'verbose_name_plural': 'historical MitreTechniques'},
        ),
        migrations.AlterModelOptions(
            name='mitretactic',
            options={'verbose_name_plural': 'MitreTatics'},
        ),
        migrations.AlterModelOptions(
            name='mitretechnique',
            options={'verbose_name_plural': 'MitreTechniques'},
        ),
        migrations.AlterModelTable(
            name='mitretactic',
            table='MitreTatics',
        ),
        migrations.AlterModelTable(
            name='mitretechnique',
            table='MitreTechniques',
        ),
    ]
