# Generated by Django 3.2.16 on 2023-05-23 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_auto_20230523_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detectionsystem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_systems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mitretactic',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitre_tactics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mitretechnique',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitre_techniques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
