# Generated by Django 3.2.16 on 2023-05-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230524_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrule',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Informational', 'Informational')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rule',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Informational', 'Informational')], max_length=20),
        ),
    ]
