# Generated by Django 3.2.16 on 2023-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20230524_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rules', to='home.Tag'),
        ),
    ]
