# Generated by Django 3.2.16 on 2023-05-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20230524_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='mitre_tactics',
            field=models.ManyToManyField(related_name='rules', to='home.MitreTactic'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='mitre_techniques',
            field=models.ManyToManyField(related_name='rules', to='home.MitreTechnique'),
        ),
    ]
